### ISSUE TITLE
Stall the Cargo Intake

### ISSUE THREAD

**Issue by duane701** [FRC701/valkyrie#121]
In order to hold the cargo in the intake, the motor roller should be stalled in order to hold the ball.

Experiments will need to be done to find the stall value required to hold the ball. 🏀 

Challenges
* %VBus is dependent on the battery. Can we do current control instead?
* recompiling to change the value is a hassle. Make the setting a preference that is read on initialization. This moves to a reboot instead of a compile and download.

(Note: we should avoid reading preferences on every robot cycle, reading preferences is slow.)

**Comment by duane701** [comment]
Add RunCargoRoller to FullCargoIntake with the value set to a preference (on construction).

The preference is changed when the code is rebooted.

**Comment by NWSchallock** [comment]
closed in #130
